// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// csound_impl
int csound_impl(String orchestra, String score, String options);
RcppExport SEXP rsound_csound_impl(SEXP orchestraSEXP, SEXP scoreSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type orchestra(orchestraSEXP);
    Rcpp::traits::input_parameter< String >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< String >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(csound_impl(orchestra, score, options));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"rsound_csound_impl", (DL_FUNC) &rsound_csound_impl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsound(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
