# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
csound_impl <- function(orchestra, score, options) {
    .Call('rsound_csound_impl', PACKAGE = 'rsound', orchestra, score, options)
}

